### ISSUE TITLE
Evaluate MeasureReport for measures that have numerator/denominator or for faceted reports

### ISSUE THREAD

**Issue by DavidPyke** [AudaciousInquiry/saner-ig#11]
Hans: For this bed capacity use case Group looks sufficient. For others that need numerator/denominator, it will not be (unless you use multiple properties rather than the construct MeasureReport already has). MeasureReport does not require denominators, can just be a number, so seems appropriate as we are reporting on measures effectively.

MeasureReport is not really more complicated while with there is also increased use of MeasureReport with DEQM/Da Vinci that would make that consistency from the start appealing.

**Comment by keithboone** [comment]
Added to hot topics for Wednesday's discussion

**Comment by jmandel** [comment]
Notes from my perspective: In my example at https://gist.github.com/jmandel/41f47088085cf4633506b43438925389#file-tracking-examples-saner-json-L45, you can kind of see in the Group.name that we're building up a facet structure: the group is called "Active, Unoccupied, Non-isolating ICU Beds in Hospital A Ward 1". But if you wanted to report on different aspects (e.g., swap Occupied-> Closed, or Non-isolating->ICU, or ICU->Acute, or any other combination), then you need to create a combinatorial number of groups to express this. Whereas MeasureReport supports built-in faceting, so you can say all this stuff (summary, and breakdowns by characteristic or combination of characteristics) in a single place.

**Comment by keithboone** [comment]
The combinatorics are still there, you are just playing whack-a-mole with complexity.  It's either in the Bundle containing the batch updating the Group resources, or it's all in one MeasureReport.

**Comment by keithboone** [comment]
To me, the principle value of Group is that it allows one to segregate the reporting to departmental systems b/c not everyone has one system for their whole facility.  ICU might have a central monitoring station that can do detailed reporting on beds and equipment, ED could be another system, and the EHR data might cover everything else.

**Comment by jmandel** [comment]
From discussion on today's call: even if you have 3 distinct systems, they could each produce a distinct `MeasureReport`. (There's no hard requirement that they *need* to be aggregated, but there's a clear path for faceting/aggregation for the set of data *within* the control of the preparing system.)

**Comment by DavidPyke** [comment]
Resolved with move to MeasureReport
