### ISSUE TITLE
Characteristic constraints should be applied on each slice, not "all slices"

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/saner-ig#13]
This is subtle, but I *think* I'm correct... when I look at:

![image](https://user-images.githubusercontent.com/313089/77547517-4a9c2000-6e7b-11ea-937a-992af5e66391.png)

It says that *no slice* is allowed to set `exclude` to `true`. But the slicing on `Group.characteristic` is left as "open", so in theory we'd preventing sub-profiles from adding exclusion characteristics here. I think the "right" thing to do is leave slicing "open," but instead of applying this `exclude: false` across all slices, just repeat it in each of the ~4 slices we directly define.

**Comment by keithboone** [comment]
Agreed
