### ISSUE TITLE
Don't prohibit Group.member

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/saner-ig#2]
Given that `Group.actual` is fixed to `true`, it'd be nice not to *prevent* a system from enumerating specific beds.

![image](https://user-images.githubusercontent.com/313089/77362397-d9475a80-6d1e-11ea-86cd-fa5b746233ac.png)

I'd love it if we could say "We have 20 ICU beds free" and also "BTW here's the enumerated set of them" (even if the latter is strictly optional). Gives us room to grow.

**Comment by keithboone** [comment]
Right, I thought about that later.  We don't WANT to require it, but we don't want to prohibit it either.
Reminds me that I should have a look at what's "summary" and what should be "must support", and what the ramifications of each are.

**Comment by keithboone** [comment]
Fixed

**Comment by jmandel** [comment]
Thansk! 

@keithboone quick note, if you add "closes #2 [...]" to your git commit message, this'll create links from here to the commit where you fixed it (though I understand this only becomes *useful* as of now, when you've got the .fsh source files checked into this repo).
