### ISSUE TITLE
Create a Google Sheet of measures, focused on FEMA + CDC requirements

### ISSUE THREAD

**Issue by jmandel** [AudaciousInquiry/saner-ig#33]
Create a Google Sheet based on data from [Michael's zulip post](https://chat.fhir.org/#narrow/stream/226195-Covid-19-Response/topic/CDC.20Page/near/192180047)

**Comment by DavidPyke** [comment]
Done.  Shared with Michael, Hans, and Keith
View access at https://docs.google.com/spreadsheets/d/1r8RFNkqzHQeelM6wHuuoURcyh57PCvaPrj-eYNySrUQ/edit?usp=sharing

**Comment by jmandel** [comment]
Done at https://docs.google.com/spreadsheets/d/1r8RFNkqzHQeelM6wHuuoURcyh57PCvaPrj-eYNySrUQ/edit (Thanks @DavidPyke !)

**Comment by hbuitendijk** [comment]
Linked to the spreadsheet here: https://github.com/AudaciousInquiry/saner-ig/wiki/Measure-Summary.   Please move if there is a better space.
